version: "3.7"

services:

  postgres_database:
    image: postgres:13-alpine
    ports:
      - 54327:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: inventoryDB
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    links:
      - postgres_database
    depends_on:
      - postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: inventoryDB
      POSTGRES_HOST: postgres_database
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
